### ISSUE TITLE
Plugin throws exception with latest EAP 14

### ISSUE THREAD

**Issue by derkork** [rkhmelyuk/multirun#22]
It looks like some API that the plugin uses has been changed.

```
com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/configurations/RunProfile;Lcom/intellij/execution/Executor;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/openapi/project/Project;Lcom/intellij/execution/configurations/RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/execution/RunnerAndConfigurationSettings;Ljava/lang/String;)V
java.lang.NoSuchMethodError: com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/configurations/RunProfile;Lcom/intellij/execution/Executor;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/openapi/project/Project;Lcom/intellij/execution/configurations/RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/execution/RunnerAndConfigurationSettings;Ljava/lang/String;)V
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:91)
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:211)
    at com.khmelyuk.multirun.MultirunRunnerState.execute(MultirunRunnerState.java:63)
    at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:38)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:48)
    at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:202)
    at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:244)
    at com.intellij.openapi.project.DumbServiceImpl.access$600(DumbServiceImpl.java:52)
    at com.intellij.openapi.project.DumbServiceImpl$8.run(DumbServiceImpl.java:376)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:722)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:551)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by rkhmelyuk** [comment]
Thanks! I will merge and release today.

**Comment by derkork** [comment]
Cool :) I'd appreciate it if you could give this some test on your end. It works on my projects, but that doesn't mean that I didn't introduce some bugs.

**Comment by rkhmelyuk** [comment]
Merged in. Going to publish in next couple of hours. Thanks again! It works perfect :)
