### ISSUE TITLE
NoSuchMethodError when running on March 1, 2016 EAP

### ISSUE THREAD

**Issue by bbrudnoy** [rkhmelyuk/multirun#38]
This happened upon attempting and failing to execute a Multirun configuration. IJ build information is:

> IntelliJ IDEA (Minerva) IU-145.184.1
> Build #IU-145.184, built on March 1, 2016
> JRE: 1.8.0_40-release-b132 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```
com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/configurations/RunProfile;Lcom/intellij/execution/Executor;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/openapi/project/Project;Lcom/intellij/execution/configurations/RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/execution/RunnerAndConfigurationSettings;Ljava/lang/String;)V
java.lang.NoSuchMethodError: com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/configurations/RunProfile;Lcom/intellij/execution/Executor;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/openapi/project/Project;Lcom/intellij/execution/configurations/RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/execution/RunnerAndConfigurationSettings;Ljava/lang/String;)V
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:91)
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:211)
    at com.khmelyuk.multirun.MultirunRunnerState.execute(MultirunRunnerState.java:63)
    at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
    at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:389)
    at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:291)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:432)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:121)
    at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:116)
    at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:67)
    at com.intellij.execution.impl.ExecutionManagerImpl$7.run(ExecutionManagerImpl.java:516)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:370)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by navels** [comment]
+1 for getting an update compatible with the latest IJ 16 EAP

**Comment by rkhmelyuk** [comment]
I'm not sure I'll be supporting IJ 16 or later. I'd recommend using built-in support for running multiple configurations https://www.jetbrains.com/idea/help/run-debug-configuration-compound.html

However, feel free to checkout Multirun source code and maybe you can get it working.

**Comment by navels** [comment]
Thanks for the tip, I didn't know about the compound runner.  Unfortunately it seems to only work in Run mode, not Debug :(

Ugh, there is also no "Stop Compound" equivalent to "Stop Multirun".
