### ISSUE TITLE
IDE Internal Error

### ISSUE THREAD

**Issue by timofeev-denis** [rkhmelyuk/multirun#57]
IDEA 2017.1 and 2017.2 give error "IDE internal error occurred".

Detailed error message:

Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@27b17456 Current thread: Thread[ApplicationImpl pooled thread 9,4,Idea Thread Group] 423088006 SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.1.5#IU-171.4694.70 IDEA, eap:false, os:Windows 7 6.1, java-version:JetBrains s.r.o 1.8.0_112-release-736-b21,6,main] 111334165

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:493)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.b(ApplicationImpl.java:1109)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1098)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getStripeTitle(ToolWindowImpl.java:436)
	at com.intellij.openapi.wm.impl.content.ContentLayout.updateIdLabel(ContentLayout.java:74)
	at com.intellij.openapi.wm.impl.content.TabContentLayout.update(TabContentLayout.java:424)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.b(ToolWindowContentUi.java:233)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.propertyChange(ToolWindowContentUi.java:229)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at com.intellij.ui.content.impl.ContentImpl.setPinned(ContentImpl.java:243)
	at com.khmelyuk.multirun.MultirunRunnerState$1$1.startNotified(MultirunRunnerState.java:133)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy16.startNotified(Unknown Source)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper$2.startNotified(J2EEProcessHandlerWrapper.java:103)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
	at com.sun.proxy.$Proxy16.startNotified(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.startNotify(ProcessHandler.java:71)
	at com.intellij.execution.process.BaseOSProcessHandler.startNotify(BaseOSProcessHandler.java:163)
	at com.intellij.javaee.run.execution.LocalJavaeeServerProcessHandler.startNotify(LocalJavaeeServerProcessHandler.java:145)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper$3.onProcess(J2EEProcessHandlerWrapper.java:155)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper$ProcessCall.lambda$new$0(J2EEProcessHandlerWrapper.java:363)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by navels** [comment]
What's your plugin version?

**Comment by timofeev-denis** [comment]
I've tried version 1.7 with IDEA 2017.2.1 and version 1.6 with 2017.1.5 on another computer.

**Comment by navels** [comment]
Can you provide a github project that reproduces this problem?  I'm not encountering this exception.
