### ISSUE TITLE
Access is allowed from event dispatch thread with IW lock only.

### ISSUE THREAD

**Issue by theotherp** [rkhmelyuk/multirun#77]
```
Access is allowed from event dispatch thread with IW lock only.

java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy50.startNotified(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.startNotify(ProcessHandler.java:57)
	at com.intellij.execution.process.BaseOSProcessHandler.startNotify(BaseOSProcessHandler.java:107)
	at com.intellij.javaee.appServers.run.execution.LocalJavaeeServerProcessHandler.startNotify(LocalJavaeeServerProcessHandler.java:150)
	at com.intellij.javaee.appServers.run.execution.J2EEProcessHandlerWrapper$3.onProcess(J2EEProcessHandlerWrapper.java:161)
	at com.intellij.javaee.appServers.run.execution.J2EEProcessHandlerWrapper$ProcessCall.lambda$new$0(J2EEProcessHandlerWrapper.java:388)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@2865f9f2
Current thread: Thread[J2EEProcessHandlerWrapper Pool,4,Idea Thread Group] 1932265081
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 833583447
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1088)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1063)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1100)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateAllToolbarsImmediately(ActionToolbarImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateAllToolbarsImmediately(ActionToolbarImpl.java:72)
	at com.intellij.openapi.wm.impl.content.TabContentLayout.layout(TabContentLayout.java:215)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.update(ToolWindowContentUi.java:247)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1$1.propertyChange(ToolWindowContentUi.java:99)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at com.intellij.ui.content.impl.ContentImpl.setDisplayName(ContentImpl.java:112)
	at com.khmelyuk.multirun.MultirunRunnerState$1$1.startNotified(MultirunRunnerState.java:138)
	at jdk.internal.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy50.startNotified(Unknown Source)
	at com.intellij.javaee.appServers.run.execution.J2EEProcessHandlerWrapper$2.startNotified(J2EEProcessHandlerWrapper.java:109)
	... 22 more
```

IntelliJ 2020.3

**Comment by rkhmelyuk** [comment]
Hi theotherp, as part of https://github.com/rkhmelyuk/multirun/issues/78, I have made a few changes. I think it should cover this issue as well. However, new version 1.13 is only for 2021.2+ versions of IDEs.

**Comment by theotherp** [comment]
This seems to have been fixed, thanks.
