### ISSUE TITLE
Parent has already been disposed

### ISSUE THREAD

**Issue by theotherp** [rkhmelyuk/multirun#83]
```
com.intellij.util.IncorrectOperationException: Sorry but parent: com.intellij.execution.ui.RunContentDescriptor#1362488894(Run <Java Run Configuration>) (class com.intellij.execution.ui.RunContentDescriptor) has already been disposed (see the cause for stacktrace) so the child: <Maven Run Configuration> (class com.intellij.execution.runners.ExecutionEnvironment) will never be disposed
    at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:53)
    at com.intellij.openapi.util.Disposer.register(Disposer.java:73)
    at com.intellij.execution.runners.ExecutionEnvironment.setContentToReuse(ExecutionEnvironment.java:202)
    at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:209)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:169)
    at com.intellij.execution.ExecutionManager.startRunProfileWithPromise(ExecutionManager.kt:74)
    at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:107)
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
    at com.khmelyuk.multirun.MultirunRunnerState.access$800(MultirunRunnerState.java:44)
    at com.khmelyuk.multirun.MultirunRunnerState$1.lambda$processStarted$1(MultirunRunnerState.java:263)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

The multirun runs a java run config first and then a maven run config.

Version 1.13 with IntelliJ 2021.3 EAP.

**Comment by zorba128** [comment]
Same here; quite annoying, as makes multirun skip some of configured run configuration.
All run configurations are scala application in my case.

com.intellij.util.IncorrectOperationException: Sorry but parent: com.intellij.execution.ui.RunContentDescriptor#25290713(....) has already been disposed (see the cause for stacktrace) so the child: (...) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:53)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:73)
	at com.intellij.execution.runners.ExecutionEnvironment.setContentToReuse(ExecutionEnvironment.java:202)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:209)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:169)
	at com.intellij.execution.ExecutionManager.startRunProfileWithPromise(ExecutionManager.kt:74)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:107)
	at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
	at com.khmelyuk.multirun.MultirunRunnerState.access$800(MultirunRunnerState.java:44)
	at com.khmelyuk.multirun.MultirunRunnerState$1.lambda$processStarted$1(MultirunRunnerState.java:263)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
