### ISSUE TITLE
"Access is allowed from event dispatch thread only" is back in 1.13

### ISSUE THREAD

**Issue by theotherp** [rkhmelyuk/multirun#85]
```
Access is allowed from event dispatch thread only

java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:247)
	at com.sun.proxy.$Proxy51.startNotified(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.startNotify(ProcessHandler.java:58)
	at com.intellij.execution.process.BaseOSProcessHandler.startNotify(BaseOSProcessHandler.java:108)
	at com.intellij.javaee.appServers.run.execution.LocalJavaeeServerProcessHandler.startNotify(LocalJavaeeServerProcessHandler.java:167)
	at com.intellij.javaee.appServers.run.execution.J2EEProcessHandlerWrapper$3.onProcess(J2EEProcessHandlerWrapper.java:160)
	at com.intellij.javaee.appServers.run.execution.J2EEProcessHandlerWrapper$ProcessCall.lambda$new$0(J2EEProcessHandlerWrapper.java:386)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[J2EEProcessHandlerWrapper Pool,4,main] 1552104557
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 109755347
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1035)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1018)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1111)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1106)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.updateSingleContentView(SingleContentLayout.kt:187)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.tryUpdateContentView(SingleContentLayout.kt:95)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.update(SingleContentLayout.kt:69)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.update(ToolWindowContentUi.java:261)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1$1.propertyChange(ToolWindowContentUi.java:106)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at com.intellij.ui.content.impl.ContentImpl.setDisplayName(ContentImpl.java:110)
	at com.khmelyuk.multirun.MultirunRunnerState$1$1.startNotified(MultirunRunnerState.java:149)
	at jdk.internal.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy51.startNotified(Unknown Source)
	at com.intellij.javaee.appServers.run.execution.J2EEProcessHandlerWrapper$2.startNotified(J2EEProcessHandlerWrapper.java:108)
	... 22 more
```

with Plugin version 1.13 and IntelliJ 213.4631.20 (built on October 6, 2021)

**Comment by GTmAster** [comment]
Also usually getting this after project stop.
Multirun version: 1.13
JetBrains Rider 2021.3.3

```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 196,4,main] 1212431014
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 711855645
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1035)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1018)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1146)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1141)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.updateSingleContentView(SingleContentLayout.kt:187)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.tryUpdateContentView(SingleContentLayout.kt:95)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.update(SingleContentLayout.kt:69)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.update(ToolWindowContentUi.java:267)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1$1.propertyChange(ToolWindowContentUi.java:111)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at com.intellij.ui.content.impl.ContentImpl.setDisplayName(ContentImpl.java:110)
	at com.khmelyuk.multirun.MultirunRunnerState$1$1$1.run(MultirunRunnerState.java:197)
	at com.intellij.codeWithMe.ClientId$Companion$decorateRunnable$1.run(ClientId.kt:223)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sahlouls** [comment]
Also in 
Intellij IDEA 2022.1.2
Multirun  1.13

```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 527,4,main] 141643375
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 632200955
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1103)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1086)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.kt:926)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.registerToolWindow(BackendServerToolWindowManager.kt:89)
	at com.intellij.execution.ui.RunContentManagerImpl.registerToolWindow(RunContentManagerImpl.kt:150)
	at com.intellij.execution.ui.RunContentManagerImpl.getOrCreateContentManagerForToolWindow(RunContentManagerImpl.kt:398)
	at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.kt:382)
	at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.kt:357)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:208)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.ExecutionManager.startRunProfileWithPromise(ExecutionManager.kt:82)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:105)
	at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
	at com.khmelyuk.multirun.MultirunRunnerState.access$800(MultirunRunnerState.java:44)
	at com.khmelyuk.multirun.MultirunRunnerState$1$2.lambda$run$0(MultirunRunnerState.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by kru2** [comment]
Did anyone manage to solve this? @sahlouls
