### ISSUE TITLE
[Bug] IncorrectOperationException when running MultiRun a second time after some failed tests

### ISSUE THREAD

**Issue by MerzDaniel** [rkhmelyuk/multirun#88]
**What did I do**
- Run a MultiRun run config with tests and code checks (3 run configs are started)
- Some of the sub runConfigs failed and got "pinned" in the run window of IntelliJ as expected
- After fixing the issues I ran the MultiRun again => the Exception from below is shown 
- After closing the pinned windows I was able to run the MultiRun again successfully

**Exception**
```
com.intellij.util.IncorrectOperationException: Sorry but parent: com.intellij.execution.ui.RunContentDescriptor#180593408(Rerun Failed Tests) (class com.intellij.execution.ui.RunContentDescriptor) has already been disposed (see the cause for stacktrace) so the child: typecheck (class com.intellij.execution.runners.ExecutionEnvironment) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:53)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:74)
	at com.intellij.execution.runners.ExecutionEnvironment.setContentToReuse(ExecutionEnvironment.java:195)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:211)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.runners.AsyncProgramRunner.execute(GenericProgramRunner.kt:47)
	at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
	at com.khmelyuk.multirun.MultirunRunnerState.access$800(MultirunRunnerState.java:44)
	at com.khmelyuk.multirun.MultirunRunnerState$1.lambda$processStarted$1(MultirunRunnerState.java:263)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by MerzDaniel** [comment]
I have this problem every single day. At the moment I always close all run config tabs before starting the multirun...
