### ISSUE TITLE
Exceptions with IntelliJ 2022.1

### ISSUE THREAD

**Issue by NicolaF** [rkhmelyuk/multirun#90]
Hi, I get a exceptions after upgrading IntelliJ:

```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:64)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.kt:429)
	at com.intellij.execution.ui.RunContentManagerImpl.updateToolWindowDecoration(RunContentManagerImpl.kt:421)
	at com.intellij.execution.ui.RunContentManagerImpl.getOrCreateContentManagerForToolWindow(RunContentManagerImpl.kt:388)
	at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.kt:382)
	at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.kt:357)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:208)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.ExecutionManager.startRunProfileWithPromise(ExecutionManager.kt:82)
	at com.intellij.debugger.impl.GenericDebuggerRunner.execute(GenericDebuggerRunner.java:65)
	at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
	at com.khmelyuk.multirun.MultirunRunnerState.lambda$execute$0(MultirunRunnerState.java:76)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:64)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.kt:429)
	at com.intellij.execution.ui.RunContentManagerImpl.updateToolWindowDecoration(RunContentManagerImpl.kt:421)
	at com.intellij.execution.ui.RunContentManagerImpl.getOrCreateContentManagerForToolWindow(RunContentManagerImpl.kt:388)
	at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.kt:382)
	at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.kt:357)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:208)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.ExecutionManager.startRunProfileWithPromise(ExecutionManager.kt:82)
	at com.intellij.debugger.impl.GenericDebuggerRunner.execute(GenericDebuggerRunner.java:65)
	at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
	at com.khmelyuk.multirun.MultirunRunnerState.access$800(MultirunRunnerState.java:44)
	at com.khmelyuk.multirun.MultirunRunnerState$1$2.lambda$run$0(MultirunRunnerState.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Cheers,
Nicolas

**Comment by Jakasha** [comment]
Also with Intellij 2022.1.1:

```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:64)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.kt:429)
	at com.intellij.execution.ui.RunContentManagerImpl.updateToolWindowDecoration(RunContentManagerImpl.kt:421)
	at com.intellij.execution.ui.RunContentManagerImpl.getOrCreateContentManagerForToolWindow(RunContentManagerImpl.kt:388)
	at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.kt:382)
	at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.kt:357)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:208)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.ExecutionManager.startRunProfileWithPromise(ExecutionManager.kt:82)
	at com.intellij.debugger.impl.GenericDebuggerRunner.execute(GenericDebuggerRunner.java:65)
	at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
	at com.khmelyuk.multirun.MultirunRunnerState.lambda$runConfigurations$1(MultirunRunnerState.java:281)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by simonstratmann** [comment]
This is getting a bit annoying. Is the plugin abandoned? I'd be willing to fix this and make an MR if I know it's going to be accepted and the next version to be released.

**Comment by quirin-buechner-mdctec** [comment]
I'd also really love to see this plugin kept alive. 

@rkhmelyuk I guess your time resources are quite limited but it would be really awesome if you could make a new release, or otherwise provide all information for the community to be able to publish a new version.

looks like the 'build.graddle' file has a target called 'publishPlugin' but it depends on the 'local.properties' file that is not checked in

**Comment by simonstratmann** [comment]
While the developer is active on the plugin site they don't respond here.

I created a version 1.13.1 which seems to fix the bugs: 
[Multirun-1.13.1.zip](https://github.com/rkhmelyuk/multirun/files/9581978/Multirun-1.13.1.zip)

The source code is here: https://github.com/simonstratmann/multirun

**Comment by rkhmelyuk** [comment]
@simonstratmann thanks for preparing the bug fix. I'll be happy to take the fix as Pull request and update the plugin.

**Comment by Threnklyn** [comment]
#95 any progress?
