### ISSUE TITLE
Cant add configuration in Startup/Connection tab

### ISSUE THREAD

**Issue by BaritskiyIllya** [rkhmelyuk/multirun#94]
- <details><summary>Tab screanshot</summary>

      ![image](https://user-images.githubusercontent.com/50331812/193280261-6c989d4c-e6eb-4613-a26f-57a2931d3c1f.png)

   </details>

  - <details><summary>IDE</summary>
    <pre>
      RubyMine 2022.2.2
      Build #RM-222.4167.28, built on September 13, 2022
      Runtime version: 17.0.4+7-b469.53 amd64
      VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
      Linux 5.15.0-30-generic
      GC: G1 Young Generation, G1 Old Generation
      Memory: 1982M
      Cores: 16
    </pre>
   </details>

  - <details><summary>IDE Registry</summary>
    <pre>
      debugger.new.debug.tool.window.view=true
      debugger.new.threads.view=true
      ruby.complete.do.block.by.space=true
      debugger.enable.breakpoints.during.evaluation=true
      documentation.show.toolbar=true
      debugger.collection.watchpoints.enabled=true
      debugger.valueTooltipAutoShowOnSelection=true
      debugger.show.values.colorful=true
    </pre>
   </details>

  - <details><summary>IDE Non-Bundled Plugins</summary>
    <pre>
        com.khmelyuk.multirun (1.13)
        com.vincentp.gruvbox-theme (0.5.5)
        com.intellij.jira (4.2.0)
        co.anbora.labs.ngrok (1.2.2)
        kg.akoikelov.intellij.rms (0.0.2)
        com.jetbrains.plugins.asp (222.4167.21)
        coderpillr.theme (1.0.0-rc.3)
        com.intellij.ideolog (203.0.30.0)
        GrepConsole (12.15.211.6693.1)
        hu.aradipatrik.onedarknative (1.5)
        pl.szymonprz.idea-cheatsh-plugin (1.3.3)
        awesome.console (0.1337.12)
        club.nutsoft.Github3Theme (1.2.0)
        DBN (3.3.2160.0)
        com.godwin.json.parser (1.4.1
        mobi.hsz.idea.gitignore (4.4.2)
        com.mallowigi (73.0.0)
        one.util.ideaplugin.screenshoter (1.7.1)
        com.intellij.plugins.gnomekeymap (213.4250.391)
        eink-theme (1.1.3)
        com.virtuslab.git-machete (3.0.1)
        com.nasller.CodeGlancePro (1.5.2)
        Remote call (1.8)
        com.jmg.codecomment (4.1)
        zielu.gittoolbox (212.9.9)
        com.karateca.jstoolbox (1.10)
        com.dekonoplyov.KeymapNationalizer (0.2.7)
        github.cweijan.test-theme (1.6)
        io.github.xiaopihai7256 (0.5.0)
        MultiHighlight (3.0.0)
        com.failfast (2.0.4)
        izhangzhihao.rainbow.brackets (6.26)
        com.intellij.plugins.html.instantEditing (222.4167.21)
        AceJump (3.8.8)
        net.ashald.envfile (3.2.2)
        Railways (0.8.17)
        ru.adelf.idea.dotenv (2022.2)
        com.refactorings.ruby.RubyRefactorings (0.1.20)
        org.nemwiz.jira-commit-message (3.0.0)
    </pre>
   </details>

  - <details><summary>System OS</summary>
    <pre>
    Current Desktop: ubuntu:GNOME
    </pre>
   </details>

  - <details><summary>Plugin error message</summary>
    <pre>
       java.lang.Throwable: Assert: must be called on EDT
	    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	    at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:61)
	    at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.kt:434)
	    at com.intellij.execution.ui.RunContentManagerImpl.updateToolWindowDecoration(RunContentManagerImpl.kt:428)
	    at com.intellij.execution.ui.RunContentManagerImpl.getOrCreateContentManagerForToolWindow(RunContentManagerImpl.kt:395)
	    at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.kt:389)
	    at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.kt:364)
	    at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:208)
	    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:171)
	    at com.intellij.execution.runners.AsyncProgramRunner.execute(GenericProgramRunner.kt:47)
	    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
	    at com.khmelyuk.multirun.MultirunRunnerState.lambda$execute$0(MultirunRunnerState.java:76)
	    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	    at java.base/java.lang.Thread.run(Thread.java:833)

    </pre>
   </details>

  - <details><summary>Plugin error message 2</summary>
    <pre>
    java.lang.Throwable: Assert: must be called on EDT
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
    at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:61)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.kt:434)
    at com.intellij.execution.ui.RunContentManagerImpl.updateToolWindowDecoration(RunContentManagerImpl.kt:428)
    at com.intellij.execution.ui.RunContentManagerImpl.getOrCreateContentManagerForToolWindow(RunContentManagerImpl.kt:395)
    at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.kt:389)
    at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.kt:364)
    at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:208)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:171)
    at com.intellij.execution.ExecutionManager.startRunProfile(ExecutionManager.kt:72)
    at com.intellij.execution.ExecutionManager.startRunProfile(ExecutionManager.kt:67)
    at com.intellij.sh.run.ShRunProgramRunner.execute(ShRunProgramRunner.java:31)
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
    at com.khmelyuk.multirun.MultirunRunnerState.lambda$execute$0(MultirunRunnerState.java:76)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    at java.base/java.lang.Thread.run(Thread.java:833)

    </pre>
   </details>

**Comment by rkhmelyuk** [comment]
Startup/Connection is not something supported by Multirun. Not sure why it is shown, maybe I need to figure out how to hide that tabs.
