### ISSUE TITLE
RuntimeExceptionWithAttachments with PhpStorm 2022.3.2

### ISSUE THREAD

**Issue by quirin-buechner-mdctec** [rkhmelyuk/multirun#96]
```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 21,4,main] 1918511978
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 111415193
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1067)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1050)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:261)
	at com.intellij.openapi.wm.impl.WindowWatcher.getFocusedWindowForProject(WindowWatcher.java:299)
	at com.intellij.openapi.wm.impl.WindowWatcher.suggestParentWindow(WindowWatcher.java:212)
	at com.intellij.openapi.wm.impl.WindowManagerImpl.suggestParentWindow(WindowManagerImpl.kt:222)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.<init>(DialogWrapperPeerImpl.java:99)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerFactoryImpl.createPeer(DialogWrapperPeerFactoryImpl.java:21)
	at com.jetbrains.rdserver.ui.dialogs.BackendDialogWrapperPeerFactory.createPeer(BackendDialogWrapperPeerFactory.kt:31)
	at com.intellij.openapi.ui.DialogWrapper.createPeer(DialogWrapper.java:851)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:226)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:218)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:211)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:42)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:84)
	at com.intellij.execution.impl.RunDialog$1.<init>(RunDialog.java:108)
	at com.intellij.execution.impl.RunDialog.editConfiguration(RunDialog.java:108)
	at com.khmelyuk.multirun.MultirunRunnerState.checkRunConfiguration(MultirunRunnerState.java:305)
	at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:101)
	at com.khmelyuk.multirun.MultirunRunnerState$1.lambda$processStarted$0(MultirunRunnerState.java:116)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rkhmelyuk** [comment]
Is this still happening?

**Comment by tveimo** [comment]
Just happened now with Goland v2023.3.2 (Build #GO-233.13135.104, built on December 20, 2023)

```com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 193,4,main] 1503962968 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 83043173
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:143)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:65)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:262)
	at com.intellij.openapi.wm.impl.WindowWatcher.getFocusedWindowForProject(WindowWatcher.java:298)
	at com.intellij.openapi.wm.impl.WindowWatcher.suggestParentWindow(WindowWatcher.java:211)```

**Comment by quirin-buechner-mdctec** [comment]
For me everything is fine with PhpStorm 2023.3.2 and v14 of the plugin. Great! @rkhmelyuk  🥇
