### ISSUE TITLE
Not compatible with IntelliJ 2023.3.1

### ISSUE THREAD

**Issue by Candide7** [rkhmelyuk/multirun#99]
Hello,
Firstly I want to thank you for the maintenance of this plugin that I use everyday!
Unfortunately, the new intelliJ version is not compatible with the plugin as you may know.
Have you planned to release a new version in a near future please?
Regards,

**Comment by rkhmelyuk** [comment]
Hi there, Let me check it in next few days. I do not use Multirun currently, so wasn't aware it's not working.

**Comment by Candide7** [comment]
I don't face the issue anymore. I don't understand why...

**Comment by kidsacademyteam** [comment]
Hmmm... Still don't see plugin in Idea's marketplace.
JetBrain's marketplace says "Not compatible with the version of your running IDE (IntelliJ IDEA 2023.3.2)"
So issue is valid.

UPD:
IDEA 2023.2.5 - works
IDEA 2023.3+ - doesn't

**Comment by Candide7** [comment]
Actually I've got a warning caused by:

java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.kt:484)
	at com.intellij.execution.ui.RunContentManagerImpl.updateToolWindowDecoration(RunContentManagerImpl.kt:455)
	at com.intellij.execution.ui.RunContentManagerImpl.getOrCreateContentManagerForToolWindow(RunContentManagerImpl.kt:422)
	at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.kt:416)
	at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.kt:391)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile(ExecutionManagerImpl.kt:251)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.kt:213)
	at com.intellij.execution.ExecutionManager.startRunProfileWithPromise(ExecutionManager.kt:83)
	at com.intellij.debugger.impl.GenericDebuggerRunner.execute(GenericDebuggerRunner.java:66)
	at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:273)
	at com.khmelyuk.multirun.MultirunRunnerState.lambda$execute$0(MultirunRunnerState.java:76)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)


But still the plugin is working...
(I've upgraded to 2023.3.2 and same result)

**Comment by Calfur** [comment]
You can see on the store page that the compatibility range of the release `1.13` is `2021.2` - `2023.2.5`:
https://plugins.jetbrains.com/plugin/7248-multirun/versions/stable

**Comment by rkhmelyuk** [comment]
I have a working build that should work for 2023.3.* versions.

**Comment by rkhmelyuk** [comment]
I have also a fix for `java.lang.Throwable: Assert: must be called on EDT` exception.

**Comment by rkhmelyuk** [comment]
New version is uploaded, but it will need to be first reviewed by JetBrains team before it is ready to download. It might take 2 business days.

**Comment by rkhmelyuk** [comment]
New version 1.14 is available right now. Please check if it works for you. https://plugins.jetbrains.com/plugin/7248-multirun/versions/stable/459944

**Comment by Calfur** [comment]
I have tested it, it works on my side. 🎉

- I got a notification inside IntelliJ that I can update the extension
- After updating and restarting IntelliJ I was able to run an existing Multirun configuration successfully

Thank you @rkhmelyuk for the fix and the clear communication

**Comment by rkhmelyuk** [comment]
Awesome, thank you for confirmation it works.

**Comment by Candide7** [comment]
Thank you @rkhmelyuk for your responsiveness!
